-- ============================================================
-- STEP 1: สร้าง CDSS_DRUG_MAP table
-- ============================================================
CREATE TABLE CDSS_DRUG_MAP (
  DRUG_MAP_ID   NUMBER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  HIS_DRUG_CODE VARCHAR2(50)   NOT NULL,
  HIS_DRUG_NAME VARCHAR2(300),
  DRUG_GROUP    VARCHAR2(100)  NOT NULL,
  IS_ACTIVE     CHAR(1)        DEFAULT 'Y',
  CREATED_AT    DATE           DEFAULT SYSDATE,
  CREATED_BY    VARCHAR2(100)
)
